use crate::gx::*;
use crate::shader::*;

pub static LIGHTMAPPED_SHADER: Shader = Shader {
    stages: [
        Some(TevStage {
            color_in: [
                TevColorIn::Constant0,
                TevColorIn::Constant0,
                TevColorIn::Constant0,
                TevColorIn::TexColor,
            ],
            color_op: TevOp::Add,
            color_bias: TevBias::Zero,
            color_scale: TevScale::K1,
            color_clamp: false,
            color_dst: TevReg::Prev,
            alpha_in: [
                TevAlphaIn::Constant0,
                TevAlphaIn::Constant0,
                TevAlphaIn::Constant0,
                TevAlphaIn::Constant0,
            ],
            alpha_op: TevOp::Add,
            alpha_bias: TevBias::Zero,
            alpha_scale: TevScale::K1,
            alpha_clamp: false,
            alpha_dst: TevReg::Prev,
            tex_coord: TevTexCoord::TexCoord0,
            tex_map: TevTexMap::TEXMAP0,
            channel: TevChannel::Null,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    num_chans: 0,
    tex_gens: [
        Some(TexGen {
            type_: TexGenType::Mtx2x4,
            src: TexGenSrc::TexCoord0,
            mtx_index: TexMtxIndex::IDENTITY,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
};
