[package]
name = "build-gcm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
byteorder = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
relocation = { path = "../../shared/relocation" }
