[package]
name = "font-gx"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
test = false
bench = false

[dependencies]
gamecube-shader = { path = "../gamecube-shader", default-features = false }
ogc-sys = { path = "../ogc-sys", default-features = false }
