[package]
name = "apploader"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "apploader"
test = false
bench = false

[dependencies]
aligned = "0.4"
bytemuck = { version = "1", features = ["derive"] }
panic-never = "0.1"
