[workspace]
members = [
    "fully-occupied",
    "gx",
    "inception-render-common",
    "mvbitfield",
    "mvbitfield-proc-macro",
    "no-std-ftp",
    "no-std-io",
    "recursive-iter",
    "relocation",
    "source-reader",
    "texture-atlas",
    "texture-format",
]
