[package]
name = "texture-format"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1"
half = { version = "2", features = ["num-traits"] }
num-traits = "0.2"
stb_dxt = "0.1"
